N=8

x_t=[2,1,3,4,2,8,4,3];
X_f=zeros(1,8);


for k=1:N
  for n=1:N
    X_f(k) = X_f(k) + x_t(n) * exp(-i*2*pi*k*n/N);
  end
end

%X_f

exp(-i*2*pi*1*0/N)
exp(-i*2*pi*1*1/N)
exp(-i*2*pi*1*2/N)
exp(-i*2*pi*1*3/N)
exp(-i*2*pi*1*4/N)
exp(-i*2*pi*1*5/N)
exp(-i*2*pi*1*6/N)



k=0;
X_1 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)

k=1;
X_2 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)
    
k=2;
X_3 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)

k=3;
X_4 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)
    
k=4;
X_5 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)
    
k=5;
X_6 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)
    
k=6;
X_7 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)
    
k=7;
X_8 = x_t(1) * exp(-i*2*pi*k*0/N) ...
    + x_t(2) * exp(-i*2*pi*k*1/N) ...
    + x_t(3) * exp(-i*2*pi*k*2/N) ...
    + x_t(4) * exp(-i*2*pi*k*3/N) ...
    + x_t(5) * exp(-i*2*pi*k*4/N) ...
    + x_t(6) * exp(-i*2*pi*k*5/N) ...
    + x_t(7) * exp(-i*2*pi*k*6/N) ...
    + x_t(8) * exp(-i*2*pi*k*7/N)
    

%sum(exp(-i*2*pi*[0:N-1]'*0).*x_t)

fft(x_t)