
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/negierer_top 

module negierer(a, b);
  input [12:0] a;
  output [12:0] b;
  wire [12:0] a;
  wire [12:0] b;
  wire n_1, n_2, n_3, n_4, n_5, n_6, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_15, n_17, n_19;
  wire n_21, n_23, n_25, n_27, n_29, n_31, n_33;
  XNR20 g317(.A (n_33), .B (a[12]), .Q (b[12]));
  ADD21 g318(.A (n_31), .B (n_8), .CO (n_33), .S (b[11]));
  ADD21 g319(.A (n_29), .B (n_2), .CO (n_31), .S (b[10]));
  ADD21 g320(.A (n_27), .B (n_11), .CO (n_29), .S (b[9]));
  ADD21 g321(.A (n_25), .B (n_10), .CO (n_27), .S (b[8]));
  ADD21 g322(.A (n_23), .B (n_5), .CO (n_25), .S (b[7]));
  ADD21 g323(.A (n_21), .B (n_6), .CO (n_23), .S (b[6]));
  ADD21 g324(.A (n_19), .B (n_4), .CO (n_21), .S (b[5]));
  ADD21 g325(.A (n_17), .B (n_9), .CO (n_19), .S (b[4]));
  ADD21 g326(.A (n_15), .B (n_12), .CO (n_17), .S (b[3]));
  ADD21 g327(.A (n_13), .B (n_1), .CO (n_15), .S (b[2]));
  ADD21 g328(.A (n_3), .B (n_7), .CO (n_13), .S (b[1]));
  CLKIN2 g329(.A (a[3]), .Q (n_12));
  CLKIN2 g330(.A (a[9]), .Q (n_11));
  CLKIN2 g331(.A (a[8]), .Q (n_10));
  CLKIN2 g332(.A (a[4]), .Q (n_9));
  CLKIN2 g333(.A (a[11]), .Q (n_8));
  CLKIN2 g334(.A (a[1]), .Q (n_7));
  CLKIN2 g335(.A (a[6]), .Q (n_6));
  CLKIN2 g336(.A (a[7]), .Q (n_5));
  CLKIN2 g337(.A (a[5]), .Q (n_4));
  INV2 g338(.A (a[0]), .Q (n_3));
  CLKIN2 g339(.A (a[10]), .Q (n_2));
  CLKIN2 g340(.A (a[2]), .Q (n_1));
endmodule

module negierer_top(a, b);
  input [12:0] a;
  output [12:0] b;
  wire [12:0] a;
  wire [12:0] b;
  wire UNCONNECTED;
  assign b[0] = a[0];
  negierer inv(.a (a), .b ({b[12:1], UNCONNECTED}));
endmodule

