
// Generated by Cadence Encounter(R) RTL Compiler RC14.25 - v14.20-s046_1

// Verification Directory fv/Addierer_TOP 

module addierer(a, b, x);
  input [12:0] a, b;
  output [12:0] x;
  wire [12:0] a, b;
  wire [12:0] x;
  wire n_0, n_1, n_2, n_4, n_6, n_8, n_10, n_12;
  wire n_14, n_16, n_18, n_20, n_22, n_24;
  INV2 g751(.A (n_24), .Q (x[12]));
  ADD31 g752(.A (n_1), .B (n_0), .CI (n_22), .CO (n_24), .S (x[11]));
  ADD31 g753(.A (a[11]), .B (b[11]), .CI (n_20), .CO (n_22), .S
       (x[10]));
  ADD31 g754(.A (a[10]), .B (b[10]), .CI (n_18), .CO (n_20), .S (x[9]));
  ADD31 g755(.A (a[9]), .B (b[9]), .CI (n_16), .CO (n_18), .S (x[8]));
  ADD31 g756(.A (a[8]), .B (b[8]), .CI (n_14), .CO (n_16), .S (x[7]));
  ADD31 g757(.A (a[7]), .B (b[7]), .CI (n_12), .CO (n_14), .S (x[6]));
  ADD31 g758(.A (a[6]), .B (b[6]), .CI (n_10), .CO (n_12), .S (x[5]));
  ADD31 g759(.A (a[5]), .B (b[5]), .CI (n_8), .CO (n_10), .S (x[4]));
  ADD31 g760(.A (a[4]), .B (b[4]), .CI (n_6), .CO (n_8), .S (x[3]));
  ADD31 g761(.A (a[3]), .B (b[3]), .CI (n_4), .CO (n_6), .S (x[2]));
  ADD31 g762(.A (a[2]), .B (b[2]), .CI (n_2), .CO (n_4), .S (x[1]));
  ADD21 g763(.A (a[1]), .B (b[1]), .CO (n_2), .S (x[0]));
  CLKIN3 g764(.A (a[12]), .Q (n_1));
  CLKIN3 g765(.A (b[12]), .Q (n_0));
endmodule

module Addierer_TOP(a, b, x);
  input [12:0] a, b;
  output [12:0] x;
  wire [12:0] a, b;
  wire [12:0] x;
  wire UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0;
  addierer mult(.a ({a[12:1], UNCONNECTED_HIER_Z}), .b ({b[12:1],
       UNCONNECTED_HIER_Z0}), .x (x));
endmodule

